# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch


# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.6682, 0.5610, 0.7983, 0.0954, 0.5672, 0.4382, 0.0139],
        [0.3753, 0.6822, 0.4732, 0.1650, 0.3479, 0.6138, 0.6758],
        [0.7893, 0.3978, 0.2222, 0.5248, 0.5716, 0.2467, 0.4832],
        [0.9369, 0.7323, 0.1805, 0.6691, 0.8096, 0.0169, 0.5004],
        [0.6113, 0.2766, 0.3359, 0.3508, 0.7731, 0.4397, 0.3182],
        [0.7986, 0.6775, 0.1145, 0.6748, 0.8468, 0.9574, 0.2447],
        [0.1519, 0.9280, 0.6256, 0.3211, 0.3942, 0.8700, 0.8572]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor2 = torch.rand(1, 7)
tensor2
# Perform matrix multiplication 
multipulated_tensor = torch.mm(tensor, tensor2.T)
print(f"{tensor.shape}, {tensor2.shape}, {multipulated_tensor.shape}")
print(f"\n{multipulated_tensor}")

torch.Size([7, 7]), torch.Size([1, 7]), torch.Size([7, 1])

tensor([[1.6365],
        [1.5963],
        [1.8785],
        [2.5389],
        [1.7296],
        [2.5601],
        [2.0305]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 42

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
tensorB = torch.rand(7, 1)

# Matrix multiply tensors
randomSeedOutput = torch.mm(tensorA, tensorB)
randomSeedOutput, randomSeedOutput.shape

(tensor([[3.2618],
         [3.4084],
         [2.4866],
         [1.4525],
         [1.7079],
         [2.7291],
         [2.9204]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
randomTensor1 = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
randomTensor2 = torch.rand(7, 1)

randomSeedOutputGPU = torch.mm(randomTensor1, randomTensor2)
randomSeedOutputGPU, randomSeedOutputGPU.shape

(tensor([[0.8613],
         [1.2761],
         [1.1540],
         [1.0134],
         [0.6783],
         [1.1122],
         [0.7266]]),
 torch.Size([7, 1]))


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "GPU" 
device
# Create two random tensors on GPU
tensor__a = torch.rand(size=(2, 3)).to(device)
tensor__b = torch.rand(size=(2, 3)).to(device)

tensor__a, tensor__b

(tensor([[0.4681, 0.6738, 0.3315],
         [0.7837, 0.5631, 0.7749]], device='cuda:0'),
 tensor([[0.8208, 0.2793, 0.6817],
         [0.2837, 0.6567, 0.2388]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
tensor_mm = torch.mm(tensor__a, tensor__b.T)
tensor_mm, tensor_mm.shape

(tensor([[0.7984, 0.6544],
         [1.3287, 0.7771]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
tensor_max = torch.max(tensor_mm)
print(tensor_max)

# Find min
tensor_min = torch.min(tensor_mm)
print(tensor_min)

tensor(1.3287, device='cuda:0')
tensor(0.6544, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
argmax_ = torch.argmax(tensor_mm)
print(argmax_)

# Find arg min
argmin_ = torch.argmin(tensor_mm)
print(argmin_)

tensor(2, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
MANUAL_SEED = 7

# Create random tensor
random_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
remove1_dim = random_tensor.squeeze()

# Print out tensors and their shapes
remove1_dim, remove1_dim.size

(tensor([0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265,
         0.9561]),
 <function Tensor.size>)