# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
import torch


# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[6.6167e-01, 2.6816e-02, 8.2354e-01, 7.7111e-01, 4.8274e-01, 2.8206e-01,
         8.3826e-01],
        [2.6614e-01, 7.9974e-01, 3.1098e-01, 6.7082e-02, 5.8370e-01, 4.8016e-01,
         9.1436e-01],
        [9.2552e-01, 2.2136e-01, 1.8252e-02, 9.0224e-01, 3.0994e-01, 5.1601e-01,
         5.2142e-01],
        [4.6776e-01, 9.3035e-01, 9.9472e-01, 7.6768e-02, 3.6333e-02, 1.9044e-02,
         8.0264e-04],
        [8.4723e-01, 1.5092e-01, 1.8048e-01, 2.2035e-01, 3.1636e-01, 2.7166e-01,
         6.0646e-02],
        [4.5391e-02, 3.1479e-01, 9.5587e-01, 1.3593e-01, 2.1889e-01, 4.4279e-01,
         4.1444e-01],
        [7.2041e-01, 2.5629e-01, 9.3132e-01, 6.4967e-01, 4.1300e-01, 2.7214e-01,
         3.9158e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2 = torch.rand(1, 7)
tensor2
# Perform matrix multiplication 
multipulated_tensor = torch.mm(tensor, tensor2.T)
print(f"{tensor.shape}, {tensor2.shape}, {multipulated_tensor.shape}")
print(f"\n{multipulated_tensor}")

torch.Size([7, 7]), torch.Size([1, 7]), torch.Size([7, 1])

tensor([[2.0900],
        [1.5362],
        [1.6928],
        [2.1035],
        [1.2427],
        [1.5011],
        [2.3000]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED = 42

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
tensorB = torch.rand(7, 1)

# Matrix multiply tensors
randomSeedOutput = torch.mm(tensorA, tensorB)
randomSeedOutput, randomSeedOutput.shape

(tensor([[3.2618],
         [3.4084],
         [2.4866],
         [1.4525],
         [1.7079],
         [2.7291],
         [2.9204]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
randomTensor1 = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
randomTensor2 = torch.rand(7, 1)

randomSeedOutputGPU = torch.mm(randomTensor1, randomTensor2)
randomSeedOutputGPU, randomSeedOutputGPU.shape

(tensor([[0.8613],
         [1.2761],
         [1.1540],
         [1.0134],
         [0.6783],
         [1.1122],
         [0.7266]]),
 torch.Size([7, 1]))


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "GPU" 
device
# Create two random tensors on GPU
tensor__a = torch.rand(size=(2, 3)).to(device)
tensor__b = torch.rand(size=(2, 3)).to(device)

tensor__a, tensor__b

(tensor([[0.4681, 0.6738, 0.3315],
         [0.7837, 0.5631, 0.7749]], device='cuda:0'),
 tensor([[0.8208, 0.2793, 0.6817],
         [0.2837, 0.6567, 0.2388]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
